name: Auto message on Creating a Issue.

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Create comment for issue
      if: github.event_name =='issues'
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{tojson(github.event.issue.number)}}
        body: Hello there!👋, @${{ github.actor }}.
      