# Don't exclude the gradlew and gradle-wrapper.jar file, it is needed to run the build
# Generate them with `gradle wrapper` if they are not present

name: Java CI with Gradle

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Gradle
      run: |
          chmod +x *
          ./gradlew clean build

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: Files
        path: build/libs/*.jar
