# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Don't exclude the mvnw and maven-wrapper.jar file, it is needed to run the build
# Generate them with `mvn wrapper:wrapper` if they are not present

name: Java CI with Maven

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@1

    - name: Build with Maven
      run: |
          chmod +x *
          ./mvnw -B clean package --file pom.xml

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: Files
        path: target/*.jar
