name: Upload Assets

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Upload Assets
      uses: actions/upload-artifact@v4
      with:
        name: Assets
        path: |
          app/*
          !app/build.gradle.kts
          !app/src/
          !app/build/
          !app/logs/
